[package]
edition = "2021"

name = "stylix"
description = "A simple lib for using Stylix"
keywords = ["stylix", "nix", "nixos"]

version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["Daniel Nussbaum <info@daniel-nussbaum.at>"]

readme = "README.md"
repository = "https://github.com/danussi/stylix-rs"
homepage = "https://github.com/danussi/stylix-rs"

[dependencies]
home-config = { version = "0.7.0", features = ["json"] }
serde = "1.0.229"
temp-env = "0.3.6"
