//! # stylix
//!
//! A Rust library for reading the color palette generated by [Stylix](https://github.com/danth/stylix).
//!
//! This library provides a simple way to access the generated color palette from your Rust applications.
//!
//! # Usage
//!
//! Add `stylix` to your `Cargo.toml` dependencies.
//!
//! Then, load the palette:
//!
//! ```rust
//! use stylix::Stylix;
//!
//! // The palette is loaded from ~/.config/stylix/palette.json
//! match Stylix::load() {
//!     Ok(palette) => {
//!         println!("Scheme: {}", palette.scheme);
//!         println!("Base00 color: R:{} G:{} B:{}", palette.base00.r, palette.base00.g, palette.base00.b);
//!     }
//!     Err(e) => {
//!         eprintln!("Failed to load stylix palette: {}", e);
//!     }
//! }
//! ```
//!
//! The `Stylix::load()` function returns a `StylixPalette` struct, containing `Color` structs for each color value (e.g., `base00`, `base01`, etc.), along with `author`, `scheme`, and `slug` strings.
//!
//! # Ratatui Color Support
//!
//! Enable the 'ratatui-color' feature for some quality of live conversion methods.
//!
//! ```rust
//! use stylix::color::ratatui_color::From;
//! use stylix::color::Color as StylixColor;
//! use ratatui_core::style::Color as RatatuiColor;
//!
//! let stylix_color = StylixColor {
//!     r: 255,
//!     g: 255,
//!     b: 255,
//! };
//!
//! let ratatui_color: RatatuiColor = RatatuiColor::Rgb(255, 255, 255);
//!
//! assert_eq!(stylix_color.into(), ratatui_color);
//!
//! ```
//!
use home_config::HomeConfig;

use crate::{
    error::StylixError,
    palette::{RawStylixPalette, StylixPalette},
};

pub mod color;
pub mod error;
pub mod palette;

pub struct Stylix;

impl Stylix {
    pub fn load() -> Result<StylixPalette, StylixError> {
        let raw_palette: RawStylixPalette = HomeConfig::with_config_dir("stylix", "palette.json")
            .json()
            .map_err(StylixError::ConfigLoadError)?;

        StylixPalette::parse(raw_palette)
    }
}

#[cfg(test)]
mod test {
    use crate::color::Color;

    use super::*;

    #[test]
    fn e2e() {
        temp_env::with_var("HOME", Some("./test/home"), || {
            let home_config = HomeConfig::with_config_dir("stylix", "palette.json");
            home_config.save(r#"{
                "base00": "282828",
                "base01": "3c3836",
                "base02": "504945",
                "base03": "665c54",
                "base04": "928374",
                "base05": "ebdbb2",
                "base06": "fbf1c7",
                "base07": "f9f5d7",
                "base08": "cc241d",
                "base09": "d65d0e",
                "base0A": "d79921",
                "base0B": "98971a",
                "base0C": "689d6a",
                "base0D": "f28534",
                "base0E": "b16286",
                "base0F": "9d0006",
                "author": "Tinted Theming (https://github.com/tinted-theming), morhetz (https://github.com/morhetz/gruvbox)&#34;, Vimjoyer (https://github.com/vimjoyer)",
                "scheme": "Vimjoyer Gruvbox Dark",
                "slug": "vimjoyer-gruvbox-dark"
            }"#).unwrap();

            let palette = Stylix::load().unwrap();
            let expected = StylixPalette {
                base00: Color{ r: 40, g: 40, b: 40},
                base01: Color{ r: 60, g: 56, b: 54},
                base02: Color{ r: 80, g: 73, b: 69},
                base03: Color{ r: 102, g: 92, b: 84},
                base04: Color{ r: 146, g: 131, b: 116},
                base05: Color{ r: 235, g: 219, b: 178},
                base06: Color{ r: 251, g: 241, b: 199},
                base07: Color{ r: 249, g: 245, b: 215},
                base08: Color{ r: 204, g: 36, b: 29},
                base09: Color{ r: 214, g: 93, b: 14},
                base0A: Color{ r: 215, g: 153, b: 33},
                base0B: Color{ r: 152, g: 151, b: 26},
                base0C: Color{ r: 104, g: 157, b: 106},
                base0D: Color{ r: 242, g: 133, b: 52},
                base0E: Color{ r: 177, g: 98, b: 134},
                base0F: Color{ r: 157, g: 0, b: 6},
                author: "Tinted Theming (https://github.com/tinted-theming), morhetz (https://github.com/morhetz/gruvbox)&#34;, Vimjoyer (https://github.com/vimjoyer)".to_owned(),
                scheme: "Vimjoyer Gruvbox Dark".to_owned(),
                slug: "vimjoyer-gruvbox-dark".to_owned(),
            };
            println!("{:?}", palette);
            assert_eq!(expected, palette);
        });
    }
}
